# frozen_string_literal: true

customize_gemfiles do
  {
    single_quotes: true,
    heading: <<~HEADING
      frozen_string_literal: true

      This file was generated by Appraisal
    HEADING
  }
end

appraise "sidekiq-6.5.x" do
  group :test do
    gem "sidekiq", "~> 6.5.0"
  end
end
